import { describe, expect, it } from 'vitest';
import { DARK, LIGHT, EASTER_EGG_THEMES, ROLES, contrast, contrastChecks, hiddenPreset, parsePreferences, themeVariables } from './ui-theme';
describe('interface themes',()=>{
 it('uses known WCAG reference ratios',()=>{expect(contrast('#000000','#FFFFFF')).toBe(21);expect(contrast('#FFFFFF','#FFFFFF')).toBe(1);});
 for(const [name,modes] of Object.entries(EASTER_EGG_THEMES)) for(const mode of ['dark','light'] as const) {
  it(`${name} ${mode} passes every documented text and control contrast pair`,()=>{const checks=contrastChecks(modes[mode]);expect(checks).toHaveLength(51);for(const check of checks)expect(check.ratio,JSON.stringify(check)).toBeGreaterThanOrEqual(check.minimum);});
 }
 it('checks the Light default while preserving the existing Dark values',()=>{for(const check of contrastChecks(LIGHT.colors))expect(check.ratio).toBeGreaterThanOrEqual(check.minimum);expect(DARK.colors['text-faint']).toBe('#5C5870');expect(themeVariables(DARK)['--grad']).toBe('linear-gradient(135deg,#8C97DB,#5568C4)');});
 it('unlocks trimmed case-insensitive names without exposing inherited object properties',()=>{expect(hiddenPreset('  NaRuTo  ','light')).toEqual(EASTER_EGG_THEMES.naruto.light);expect(hiddenPreset('KUROMI','dark')).toEqual(EASTER_EGG_THEMES.kuromi.dark);expect(hiddenPreset('constructor','dark')).toBeUndefined();expect(hiddenPreset('not a theme','dark')).toBeUndefined();expect(hiddenPreset('uwm','dark')).toBeUndefined();});
 it('supports university aliases in both modes',()=>{for(const mode of ['dark','light'] as const){expect(hiddenPreset(' MSU ',mode)).toEqual(hiddenPreset('spartans',mode));expect(hiddenPreset(' UMICH ',mode)).toEqual(hiddenPreset('wolverines',mode));}for(const name of ['sonic','goth'])expect(hiddenPreset(name,'dark')).toBeDefined();});
 it('copies presets so customization cannot mutate the defaults',()=>{const colors=hiddenPreset('naruto','dark')!;colors['bg-app']='#FFFFFF';expect(EASTER_EGG_THEMES.naruto.dark['bg-app']).toBe('#1C1A17');});
 it('rejects corrupt storage, invalid colors and replacements of locked themes',()=>{expect(parsePreferences('{')).toEqual({selected:'dark',custom:[]});expect(parsePreferences(JSON.stringify({selected:'dark',custom:[{...DARK,name:'Override'}]})).custom).toEqual([]);expect(parsePreferences(JSON.stringify({selected:'custom-a',custom:[{...LIGHT,id:'custom-a',colors:{...LIGHT.colors,'bg-app':'url(evil)'}}]}))).toEqual({selected:'dark',custom:[]});});
 it('restores valid themes and falls back when a selection was deleted',()=>{const custom={...LIGHT,id:'custom-a',name:'My theme'};expect(parsePreferences(JSON.stringify({selected:custom.id,custom:[custom]}))).toEqual({selected:custom.id,custom:[custom]});expect(parsePreferences(JSON.stringify({selected:'missing',custom:[custom]})).selected).toBe('dark');});
 it('maps all user roles and derives mode-dependent surfaces',()=>{expect(ROLES).toHaveLength(16);const light=themeVariables(LIGHT);expect(light['--card']).toBe(LIGHT.colors['bg-panel']);expect(light['--sidebar']).toBe(light['--card']);expect(light['--primary-foreground']).toBe(LIGHT.colors['text-on-accent']);expect(light['--segment-track']).not.toBe(themeVariables(DARK)['--segment-track']);expect(light['--ui-font-sans']).toBeUndefined();});
});
