// @vitest-environment node
import { accessSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { collectFiles, isExcludedDir, isExcludedFile, packSource, writeSourceArchive } from './pack-source.mjs';

function makeFixture(): string {
  const root = mkdtempSync(join(tmpdir(), 'pack-source-'));

  writeFileSync(join(root, 'keep.txt'), 'keep me');
  writeFileSync(join(root, '.env.local'), 'SECRET=1');
  writeFileSync(join(root, '.env'), 'SECRET=2');
  writeFileSync(join(root, '.DS_Store'), 'junk');
  writeFileSync(join(root, 'AGENTS.md'), 'agent notes');
  writeFileSync(join(root, 'CLAUDE.md'), 'claude notes');
  writeFileSync(join(root, 'skills-lock.json'), '{}');
  writeFileSync(join(root, 'next-env.d.ts'), '/// <reference types="next" />\n');
  writeFileSync(join(root, 'tsconfig.tsbuildinfo'), '{"fileNames":[]}');

  mkdirSync(join(root, 'node_modules', 'some-pkg'), { recursive: true });
  writeFileSync(join(root, 'node_modules', 'some-pkg', 'index.js'), 'module.exports = {};');

  mkdirSync(join(root, '.vercel'), { recursive: true });
  writeFileSync(join(root, '.vercel', 'project.json'), '{}');

  mkdirSync(join(root, '.git'), { recursive: true });
  writeFileSync(join(root, '.git', 'HEAD'), 'ref: refs/heads/main');

  mkdirSync(join(root, 'src'), { recursive: true });
  writeFileSync(join(root, 'src', 'nested.txt'), 'nested');

  mkdirSync(join(root, 'public'), { recursive: true });
  writeFileSync(join(root, 'public', 'keep-in-public.txt'), 'public asset');
  // A stale archive from a previous run - must never be re-zipped into itself.
  writeFileSync(join(root, 'public', 'dreamscape-source.zip'), 'stale zip bytes');
  writeFileSync(join(root, 'public', 'dreamscape-source.json'), '{"stale":true}');

  return root;
}

describe('isExcludedDir / isExcludedFile', () => {
  it('excludes the known directory names', () => {
    for (const name of ['node_modules', '.next', '.git', '.vercel', '.superpowers', '.agents', '.claude']) {
      expect(isExcludedDir(name)).toBe(true);
    }
    expect(isExcludedDir('src')).toBe(false);
  });

  it('excludes any dotenv file by prefix, not just .env.local', () => {
    expect(isExcludedFile('.env')).toBe(true);
    expect(isExcludedFile('.env.local')).toBe(true);
    expect(isExcludedFile('.env.production')).toBe(true);
    expect(isExcludedFile('config/.env.local')).toBe(true);
  });

  it('excludes the packer\'s own generated output by exact path only', () => {
    expect(isExcludedFile('public/dreamscape-source.zip')).toBe(true);
    expect(isExcludedFile('public/dreamscape-source.json')).toBe(true);
    // A same-named file elsewhere is not the generated artifact.
    expect(isExcludedFile('archive/dreamscape-source.zip')).toBe(false);
  });

  it('keeps an ordinary source file', () => {
    expect(isExcludedFile('src/nested.txt')).toBe(false);
  });

  // Both are .gitignore'd for the same reason - regenerated by tooling, not
  // source - and both were confirmed to leak into a real archive before
  // this rule existed (see the collectFiles test below).
  it('excludes next-env.d.ts and any *.tsbuildinfo cache file', () => {
    expect(isExcludedFile('next-env.d.ts')).toBe(true);
    expect(isExcludedFile('tsconfig.tsbuildinfo')).toBe(true);
    expect(isExcludedFile('foo.tsbuildinfo')).toBe(true);
  });
});

describe('collectFiles', () => {
  let fixture: string;

  afterEach(() => {
    if (fixture) rmSync(fixture, { recursive: true, force: true });
  });

  it('drops .env.local, node_modules and .vercel from a fixture tree, keeping ordinary files', () => {
    fixture = makeFixture();
    const relativePaths = collectFiles(fixture).map((file) => file.relativePath);

    expect(relativePaths).toContain('keep.txt');
    expect(relativePaths).toContain('src/nested.txt');
    expect(relativePaths).toContain('public/keep-in-public.txt');

    expect(relativePaths).not.toContain('.env.local');
    expect(relativePaths.some((path) => path.startsWith('node_modules/'))).toBe(false);
    expect(relativePaths.some((path) => path.startsWith('.vercel/'))).toBe(false);
  });

  it('also drops .git, AGENTS.md, CLAUDE.md, skills-lock.json, .DS_Store, generated TS files and its own stale output', () => {
    fixture = makeFixture();
    const relativePaths = collectFiles(fixture).map((file) => file.relativePath);

    expect(relativePaths.some((path) => path.startsWith('.git/'))).toBe(false);
    for (const excluded of [
      '.env',
      'AGENTS.md',
      'CLAUDE.md',
      'skills-lock.json',
      '.DS_Store',
      'next-env.d.ts',
      'tsconfig.tsbuildinfo',
      'public/dreamscape-source.zip',
      'public/dreamscape-source.json',
    ]) {
      expect(relativePaths).not.toContain(excluded);
    }
  });

  // In a linked git worktree - how this packer is meant to be run - the
  // top-level .git is a plain *file* ("gitdir: /path/to/real/.git/
  // worktrees/<name>"), not a directory, so it only trips the directory
  // exclusion in a plain clone. A first real run of this packer from a
  // worktree shipped that pointer file straight into the archive, leaking
  // a local absolute path; this pins the fix.
  it('drops .git even when it is a worktree gitdir-pointer file rather than a directory', () => {
    fixture = makeFixture();
    // makeFixture() gives .git as a directory (the plain-clone shape);
    // replace it with the worktree shape, a plain pointer file, for this case.
    rmSync(join(fixture, '.git'), { recursive: true, force: true });
    writeFileSync(join(fixture, '.git'), 'gitdir: /Users/someone/project/.git/worktrees/example\n');

    const relativePaths = collectFiles(fixture).map((file) => file.relativePath);
    expect(relativePaths).not.toContain('.git');
  });
});

describe('packSource', () => {
  let fixture: string;

  afterEach(() => {
    if (fixture) rmSync(fixture, { recursive: true, force: true });
  });

  it('archives every kept file under a top-level dreamscape/ folder and reports matching stats', () => {
    fixture = makeFixture();
    const { zip, stats } = packSource(fixture);

    // STORED entries keep filenames as literal bytes in the archive, so a
    // plain substring search is enough to confirm the path prefix without
    // needing a zip reader here too.
    const raw = zip.toString('latin1');
    expect(raw).toContain('dreamscape/keep.txt');
    expect(raw).toContain('dreamscape/src/nested.txt');
    expect(raw).not.toContain('dreamscape/.env.local');
    expect(raw).not.toContain('node_modules');

    expect(stats.files).toBe(collectFiles(fixture).length);
    expect(stats.bytes).toBe(zip.length);
    expect(new Date(stats.builtAt).toString()).not.toBe('Invalid Date');
  });
});

describe('writeSourceArchive', () => {
  let fixture: string;

  afterEach(() => {
    if (fixture) rmSync(fixture, { recursive: true, force: true });
  });

  it('writes public/dreamscape-source.zip and .json under the given root', () => {
    fixture = makeFixture();
    // Start from a clean public/ (the fixture seeds a stale archive above)
    // so this test proves writeSourceArchive replaces it, not that it was
    // already there.
    const stats = writeSourceArchive(fixture);

    const zipPath = join(fixture, 'public', 'dreamscape-source.zip');
    const jsonPath = join(fixture, 'public', 'dreamscape-source.json');
    expect(() => accessSync(zipPath)).not.toThrow();
    const written = JSON.parse(readFileSync(jsonPath, 'utf8'));
    expect(written).toEqual(stats);
  });
});
